Update pr-build.yml

diff --git a/.github/workflows/pr-build.yml b/.github/workflows/pr-build.yml
--- a/.github/workflows/pr-build.yml
+++ b/.github/workflows/pr-build.yml
@@ -1,4 +1,4 @@
-name: PR Build
+name: PR build
 
 on:
   pull_request:
@@ -7,19 +7,48 @@ on:
       - replica-master
 
 jobs:
-  build:
-    runs-on: ubuntu-24.04-s390x
+  validate:
+    runs-on: ubuntu-24.04-s390x  # Ensure this self-hosted runner exists
 
     steps:
-      - name: Checkout current repo
+      - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Update and install packages
+      - name: Install required packages
         run: |
           sudo apt update -y
-          sudo apt install -y curl git tree
+          sudo apt-get install -y file
 
-      - name: Clone another GitHub repo
+      - name: Install Python dependencies
         run: |
-          git clone https://github.com/octocat/Hello-World.git
-          ls -R Hello-World
+          pip3 install --force-reinstall -v "requests==2.31.0"
+          pip3 install --upgrade docker
+
+      - name: Set PR number
+        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
+
+      - name: Run validate_builds.py script with live logs
+        run: |
+          python3 -u gha-script/validate_builds.py ${PR_NUMBER:-false} 2>&1 | tee build_log
+          my_pid_status=${PIPESTATUS[0]}
+
+          build_size=$(stat -c %s build_log)
+
+          if [ "$my_pid_status" -ne 0 ]; then
+            echo "Script failed for PR #${PR_NUMBER}"
+            if [ "$build_size" -lt 1800000 ]; then
+              cat build_log
+            else
+              echo "Build log too large, showing last 100 lines"
+              tail -100 build_log
+            fi
+            exit 1
+          else
+            echo "Script completed successfully for PR #${PR_NUMBER}"
+            if [ "$build_size" -lt 1800000 ]; then
+              cat build_log
+            else
+              echo "Build log too large, showing last 100 lines"
+              tail -100 build_log
+            fi
+          fi
